# Generated by Django 4.0.4 on 2022-05-02 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_recipe_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='unit',
        ),
    ]
